causaly/zod-validation-error

.changeset/lovely-walls-suffer.md
LICENSE
README.md
config/jest.config.ts
lib/ValidationError.spec.ts
lib/ValidationError.ts
lib/index.ts
lib/sum.spec.ts
lib/sum.ts
lib/utils/joinPath.test.ts
lib/utils/joinPath.ts
package.json
yarn.lock

This PR is introducing a new `ValidationError` class alongside related functionality to convert `ZodError` to `ValidationError` and compose a user-friendly readable message.

Introduce ValidationError with main functionality

---

.changeset/khaki-keys-smash.md
README.md
lib/ValidationError.spec.ts
lib/ValidationError.ts
lib/index.ts

Introduce a new type-guard based on heuristics instead of `instanceof` comparison to avoid multiple-version inconsistencies.

Expose isValidationErrorLike type guard

---

.changeset/strange-baboons-relax.md
lib/ValidationError.spec.ts
lib/ValidationError.ts

Resolves #15 and more specifically the part where `zod.or()` would eventually output duplicate error messages.
Also added some missing test snapshots, to ensure consistency between test cases.

fix: handle duplicate issues produced by zod.or()

---

.changeset/tiny-kids-check.md
README.md
lib/ValidationError.spec.ts
lib/ValidationError.ts

This PR implements the following changes...
1. Make `options` argument optional in `ValidationError` constructor, so as to enable a simple `new ValidationError('foobar');` invocation;
2. Use "name" instead of "type" to power the `isValidationErrorLike()` function. _Why?_ Because `name` is already defined in the Error spec (see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/name)
3. Overwrite `toString()` to avoid printing a `ZodValidationError: ` prefix on `console.log`

Flexible ValidationError

---

.changeset/wild-oranges-raise.md
lib/ValidationError.spec.ts
lib/utils/joinPath.test.ts
lib/utils/joinPath.ts

This PR updates the `joinPath` utility function to be able to handle unicode and special-char identifiers, according to spec (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#identifiers)
Fixes #18

Increase coverage of JS identifiers in joinPath function

---

.changeset/cyan-years-count.md
lib/ValidationError.spec.ts
lib/ValidationError.ts
lib/utils/NonEmptyArray.ts
lib/utils/joinPath.test.ts
lib/utils/joinPath.ts

Before this PR, given a validation error at array position 1 the error output would read `Error X at "[1]"`. After this PR, the error output reads `Error X at index 1`.
The problem becomes more evident when you account for special characters. Previously a validation error at property "*" would yield `Error X at "["*"]"`. Now it yields `Error X at "*"` which reads much better.

Better handling for single-item paths

---

.changeset/fifty-pumas-fold.md
README.md
lib/ValidationError.spec.ts
lib/ValidationError.ts
lib/index.ts

Expose a new `fromZodIssue` method that accepts a `zod.ZodIssue` instead of a `zod.ZodError` argument and returns a `ZodValidationError`.
This is to enable the use-case of using `zod-validation-error` with https://zod.dev/ERROR_HANDLING?id=customizing-errors-with-zoderrormap.
Fixes #35

Expose new fromZodIssue method

---

.changeset/four-lions-complain.md
README.md
lib/ValidationError.spec.ts
lib/ValidationError.ts
lib/index.ts

Expose errorMap property to use with `zod.setErrorMap()` method as follows...
```typescript
import { z as zod } from 'zod';
import { errorMap } from 'zod-validation-error';
zod.setErrorMap(errorMap);
```

Expose custom errorMap property

---

.github/dependabot.yml

Major version upgrades often result to breaking the code, therefore we need to handle them separately via manual PRs.

Instruct dependabot to only update minor and patch versions

---

.github/dependabot.yml

The previous dependabot config wasn't working as anticipated. It was grouping several changes together. This is not the desired behaviour.
This PR configures dependabot to ignore major updates for all dependencies, while maintaining separate PRs for each update.

Configure dependabot to ignore major version updates for all deps

---

.changeset/popular-suns-knock.md
README.md
lib/ValidationError.test.ts
lib/ValidationError.ts
lib/config.ts
lib/errorMap.ts
lib/fromZodError.test.ts
lib/fromZodError.ts
lib/fromZodIssue.test.ts
lib/fromZodIssue.ts
lib/index.ts
lib/isValidationError.test.ts
lib/isValidationError.ts
lib/isValidationErrorLike.test.ts
lib/isValidationErrorLike.ts
lib/prefixMessage.ts
lib/toValidationError.ts

Previously, `ValidationError` accepted `Array<ZodIssue>` as 2nd parameter. Now, it accepts `ErrorOptions` which contains a `cause` property. If `cause` is a `ZodError` then it will extract the attached issues and expose them over `error.details`.
This change allows us to use `ValidationError` like a native JavaScript [Error](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/Error). For example, we can now do:
```typescript
import { ValidationError } from 'zod-validation-error';
try {
// attempt to do something that might throw an error
} catch (err) {
throw new ValidationError('Something went deeply wrong', { cause: err });
}
```
This PR fixes #210

Refactor `ValidationError` to accept `ErrorOptions` as second parameter

---

package.json

Hi!
Thanks for this great package!
I noticed when I import it and bundle my project with Rollup, the bundler chooses to use the CommonJS version.
That wouldn't be a huge problem on it's own, but Zod also gets reimported in it's CJS version and It increases my raw bundle size by 126kb.
Using the `module` key in the `package.json` is a non-standard solution which is not always recognized by the bundlers.
To solve this we can add conditional exports to the `package.json` [like they have](https://github.com/colinhacks/zod/blob/a5a9d31018f9c27000461529c582c50ade2d3937/package.json#L47-L55) it in the `zod` package.
Thanks,
zsilbi

fix: esm module import in bundlers

---

.changeset/wet-moons-sip.md
package.json

Drop `exports` declaration from `package.json` until further notice. _Why?_ Because although the configuration appears to be correct the change causes dependant modules to fail.
The `exports` change is not trivial and requires further investigation before being adopted.
Fixes #253 
cc/ @zsilbi

fix: drop exports declaration from package.json

---

lib/fromZodIssue.test.ts
lib/fromZodIssue.ts

```
Validation error: Invalid function arguments
```
```
Validation error: Invalid function return type
```
```
Validation error: Invalid function arguments; Expected number, received string at index 0
```
```
Validation error: Invalid function return type; Expected number, received string"
```

feat: nicer `z.function()` messages

---

.changeset/dull-tools-fix.md
README.md
lib/fromError.test.ts
lib/fromError.ts
lib/index.ts

This PR introduces `fromError` API, which is basically the non-curried version of the existing `toValidationError`.

feat: introduce fromError API

---

.changeset/itchy-elephants-judge.md
lib/fromZodError.test.ts
lib/fromZodError.ts

This PR was an idea which came up as an outcome from this issue https://github.com/causaly/zod-validation-error/issues/42, and simply adds a runtime check in `fromZodError` which instructs consumers to use the less strict version of it, `fromError` .

chore: add runtime check in fromZodError and throw TypeError on bad usage

---

lib/ValidationError.ts
lib/fromZodError.ts
lib/fromZodIssue.test.ts
lib/index.ts
lib/isZodErrorLike.test.ts
lib/isZodErrorLike.ts
lib/toValidationError.ts

Fixes #298 
It's possible that a user has multiple versions of `zod` installed in their project. In such case, the `instanceof` check (as part of [zod-validation-error/lib/toValidationError.ts](https://github.com/causaly/zod-validation-error/blob/b7c5af10fbedce76073af23a102bea359e383352/lib/toValidationError.ts#L9)) fails because it's checking for a different prototype than the one being used.
This is NOT really an issue with `zod-validation-error`. We are doing nothing wrong. However, given that multiple users affected by this issue, we can offer an alternative.
In this PR we are implementing a change that uses heuristics to match on `ZodError` instead of performing an `instanceof` check.

Match ZodError via heuristics instead of instanceof

---

lib/fromError.test.ts

Extend `lib/fromError.test.ts` to cover ecmascript-native errors, such as `TypeError` and `ReferenceError`.
This is to address the comments in https://github.com/causaly/zod-validation-error/issues/376

test(fromError): add coverage for ecmascript-native errors

---

README.md

We already have a `isZodErrorLike` type-guard util function but it's not documented in the docs. Users are asking for it, hence my opening this PR to update README.md.
Fixes #374

docs: add isZodErrorLike description and usage example to README.md

---

lib/v4/errorMap/custom.ts
lib/v4/errorMap/errorMap.test.ts
lib/v4/errorMap/errorMap.ts
lib/v4/errorMap/invalidElement.ts
lib/v4/errorMap/invalidKey.ts
lib/v4/errorMap/invalidStringFormat.ts
lib/v4/errorMap/invalidType.ts
lib/v4/errorMap/invalidUnion.ts
lib/v4/errorMap/invalidValue.ts
lib/v4/errorMap/notMultipleOf.ts
lib/v4/errorMap/tooBig.ts
lib/v4/errorMap/tooSmall.ts
lib/v4/errorMap/unrecognizedKeys.ts

Hello! I discovered that sometimes zod doesn't add `path` property into issue which is passed into `customError`.
As you can see [here](https://github.com/colinhacks/zod/blob/main/packages/zod/src/v4/core/util.ts#L710) `zod` has a fallback for not provided path, but doesn't pass it into `config.customError`.
Reproduction:
```js
import { z } from "zod" // types: 4.0.5
import { createErrorMap, fromError } from 'zod-validation-error/v4'; // types: 4.0.0-beta.2
z.config({
customError: createErrorMap()
});
const mySchema = z.union([z.literal('first'), z.union([z.literal('second'), z.literal('third')])])
try {
mySchema.parse(['fourth'])
} catch (err) {
// Cannot read properties of undefined (reading 'concat')
const validationError = fromError(err);
console.log(validationError.toString());
}
``` …

handle no path property in "invalid_union" issue

---

.changeset/loud-kings-shout.md
lib/v4/MessageBuilder.test.ts
lib/v4/MessageBuilder.ts

Improve handling of `zod.discriminatedUnion` which manifests as `invalid_union` with an empty array of `errors`.
```json
{
"code": "invalid_union",
"errors": [],
"note": "No matching discriminator",
"discriminator": "type",
"path": [
"type"
],
"message": "Invalid input"
}
```
Fixes #575

fix: accept custom error message in discriminated union
